### PR TITLE
update Makefile #71 #72

### PR DESCRIPTION
**Pull request by showcheap**
Close issue #71 #72

### CODE REVIEW

**Comment by herpiko** [comment]
Saya uji dulu.

**Comment by showcheap** [comment]
Oke pak @herpiko

**Comment by alunux** [comment]
@showcheap hak akses untuk `/usr/bin/blankon-session` masih belum executable.

**Comment by showcheap** [comment]
Seharusnya berapa pak permissionya? Saya nyontek permission teman teman di
folder yang sama.

**Comment by alunux** [comment]
@showcheap 755, tapi yang terpasang di `/usr/bin/blankon-session` masih 644.

**Comment by alunux** [comment]
@showcheap Aha, sorry my bad, belum dipatch sama PR ini :|

**Comment by showcheap** [comment]
Haha, belum masuk master pak. Pak piko sedang sibuk nanganin irgsh.

On Oct 11, 2017 20:37, "La Ode Muh. Fadlun Akbar" <notifications@github.com>
wrote:

@showcheap <https://github.com/showcheap> Aha, sorry my bad, belum dipatch
sama PR ini :|

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/BlankOn/manokwari/pull/93#issuecomment-335812136>, or mute
the thread

**Comment by alunux** [comment]
@showcheap pas jalanin `make` kok diakhir dia jalanin `install -m 755 blankon-session /usr/bin` juga ya?

**Comment by showcheap** [comment]
ada log pak @alunux ?

**Comment by alunux** [comment]
@showcheap https://paste.fedoraproject.org/paste/0rxG2~ML7K8zW6GuGwyWGQ/raw

**Comment by showcheap** [comment]
​Baik pak, nanti saya perbaiki scriptnya

**Comment by tuanpembual** [comment]
any update?

**Pull request merged**
