### PR TITLE
Sync with bzr

### PR DESCRIPTION
**Pull request by mdamt**
* New styling
* Panel applet fixes
* Sync with bzr

### CODE REVIEW

**Comment by dotovr** [comment]
Panel applets hidden when kill manokwari:
```
pkill manokwari
```
screenshot from 2016-06-23 23-15-02


Panel applets color not sure why this doesn't work when declare in  css element `#panel-applets` or `panel-applets`
https://github.com/BlankOn/manokwari/pull/38/files#diff-f736a18141757ae868c1f35426eb0359R10

screenshot from 2016-06-23 23-14-35

**Comment by cho2** [comment]
* sebelum `pkill manokwari`

screenshot from 2016-06-23 23-33-36

* sesudah `pakill manokwari`

screenshot from 2016-06-23 23-33-54

* coba mengganti warna panel manokwari, ternyata applet menghilang, tidak terpanggil setelah `pkill manokwari`

screenshot from 2016-06-23 23-47-03

* setelah logout dan login kembali, panel muncul seperti sedia kala

**Comment by mdamt** [comment]
Updated. Please try again.

**Comment by dotovr** [comment]
Note:
Warna aplet diatur sama aplet itu sendiri
.background {}


Dari saya sudah sip
:+1:

**Pull request merged**
